card_image: https://raw.githubusercontent.com/memextech/nextjs-firebase-functions-template/main/public/images/card-image.png
created_at: 2025-03-27 17:21:19.680000
creator_id: your name
deployment:
  last_deployed: null
  type: firebase
  url: ''
description: A template for setting up Firebase Functions with Next.js for serverless
  backend operations
domain: Web Development
features:
- Firebase Functions
- Next.js Frontend
- Firebase Authentication
- Firestore Database
- Firebase Hosting
getting_started_screen: false
getting_started_screen_index: 0
git:
  branch: main
  remote: origin
  url: https://github.com/memextech/nextjs-firebase-functions-template
hero_image: https://raw.githubusercontent.com/memextech/nextjs-firebase-functions-template/main/public/images/hero-image.png
icon: Rocket
is_published: true
pills:
- icon: Rocket
  label: Setup Firebase Functions
  prompt: Help me set up Firebase Functions with Next.js
- icon: Code
  label: Deploy Functions
  prompt: Guide me through deploying Firebase Functions
project_id: KVdt3ZUiboLojrtiGFPj
published_at: 2025-03-27 17:21:31.476000
requirements:
- description: Firebase account and project
  type: system
- description: Node.js and npm
  type: software
slug: nextjs-firebase-functions-template
storage:
  compression_enabled: true
  gcs_path: null
  last_sync: null
  max_file_size_mb: 100
  size_bytes: null
title: NextJS Firebase Functions Template
tools:
- name: Firebase
  role: Backend and Authentication
  type: platform
  version: latest
- name: Next.js
  role: Frontend Framework
  type: library
  version: latest
- name: Firebase Functions
  role: Serverless Backend
  type: platform
  version: latest
updated_at: 2025-03-27 17:21:31.476000
